SOURCES += $(INCLUDES_DIR)/text/text.cpp
SOURCES += $(INCLUDES_DIR)/text/line.cpp

include $(INCLUDES_DIR)/rwfile/Makefile
include $(INCLUDES_DIR)/sorting/Makefile
include $(INCLUDES_DIR)/strings/Makefile
include $(INCLUDES_DIR)/symbols/Makefile
